name: Run Karate Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'  # 7:00 AM IST (1:30 AM UTC)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Run Karate Tests
        run: |
          mvn clean test

      - name: Upload Full Karate Report
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports/

